/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractOptions, Options } from "web3-eth-contract";
import { Block } from "web3-eth";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { Callback, TransactionObject } from "./types";

export class ChannelManager extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    channels(
      arg0: string
    ): TransactionObject<{
      threadRoot: string;
      threadCount: string;
      exitInitiator: string;
      channelClosingTime: string;
      status: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    getChannelBalances(
      user: string
    ): TransactionObject<{
      weiHub: string;
      weiUser: string;
      weiTotal: string;
      tokenHub: string;
      tokenUser: string;
      tokenTotal: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
    }>;

    getChannelDetails(
      user: string
    ): TransactionObject<{
      txCountGlobal: string;
      txCountChain: string;
      threadRoot: string;
      threadCount: string;
      exitInitiator: string;
      channelClosingTime: string;
      status: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
    }>;

    getThread(
      sender: string,
      receiver: string,
      threadId: number | string
    ): TransactionObject<{
      weiSender: string;
      weiReceiver: string;
      tokenSender: string;
      tokenReceiver: string;
      txCount: string;
      threadClosingTime: string;
      emptiedSender: boolean;
      emptiedReceiver: boolean;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: boolean;
      7: boolean;
    }>;

    hubContractWithdraw(
      weiAmount: number | string,
      tokenAmount: number | string
    ): TransactionObject<void>;

    hubAuthorizedUpdate(
      user: string,
      recipient: string,
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      pendingWeiUpdates: (number | string)[],
      pendingTokenUpdates: (number | string)[],
      txCount: (number | string)[],
      threadRoot: string | number[],
      threadCount: number | string,
      timeout: number | string,
      sigUser: string
    ): TransactionObject<void>;

    userAuthorizedUpdate(
      recipient: string,
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      pendingWeiUpdates: (number | string)[],
      pendingTokenUpdates: (number | string)[],
      txCount: (number | string)[],
      threadRoot: string | number[],
      threadCount: number | string,
      timeout: number | string,
      sigHub: string
    ): TransactionObject<void>;

    startExit(user: string): TransactionObject<void>;

    startExitWithUpdate(
      user: (string)[],
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      pendingWeiUpdates: (number | string)[],
      pendingTokenUpdates: (number | string)[],
      txCount: (number | string)[],
      threadRoot: string | number[],
      threadCount: number | string,
      timeout: number | string,
      sigHub: string,
      sigUser: string
    ): TransactionObject<void>;

    emptyChannelWithChallenge(
      user: (string)[],
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      pendingWeiUpdates: (number | string)[],
      pendingTokenUpdates: (number | string)[],
      txCount: (number | string)[],
      threadRoot: string | number[],
      threadCount: number | string,
      timeout: number | string,
      sigHub: string,
      sigUser: string
    ): TransactionObject<void>;

    emptyChannel(user: string): TransactionObject<void>;

    startExitThread(
      user: string,
      sender: string,
      receiver: string,
      threadId: number | string,
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      proof: (string | number[])[],
      sig: string
    ): TransactionObject<void>;

    startExitThreadWithUpdate(
      user: string,
      threadMembers: (string)[],
      threadId: number | string,
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      proof: (string | number[])[],
      sig: string,
      updatedWeiBalances: (number | string)[],
      updatedTokenBalances: (number | string)[],
      updatedTxCount: number | string,
      updateSig: string
    ): TransactionObject<void>;

    challengeThread(
      sender: string,
      receiver: string,
      threadId: number | string,
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      txCount: number | string,
      sig: string
    ): TransactionObject<void>;

    emptyThread(
      user: string,
      sender: string,
      receiver: string,
      threadId: number | string,
      weiBalances: (number | string)[],
      tokenBalances: (number | string)[],
      proof: (string | number[])[],
      sig: string
    ): TransactionObject<void>;

    nukeThreads(user: string): TransactionObject<void>;

    totalChannelWei(): TransactionObject<string>;
    totalChannelToken(): TransactionObject<string>;
    hub(): TransactionObject<string>;
    NAME(): TransactionObject<string>;
    approvedToken(): TransactionObject<string>;
    challengePeriod(): TransactionObject<string>;
    VERSION(): TransactionObject<string>;
    getHubReserveWei(): TransactionObject<string>;
    getHubReserveTokens(): TransactionObject<string>;
  };
  events: {
    DidHubContractWithdraw(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    DidUpdateChannel(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    DidStartExitChannel(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    DidEmptyChannel(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    DidStartExitThread(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    DidChallengeThread(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    DidEmptyThread(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    DidNukeThreads(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
