#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

cd ..

[ -e .env-vars ] && . .env-vars
. ./development/env-vars

if [[ -z "${1-}" ]]; then
    ./node_modules/.bin/concurrently -n "csw,hub" "node --nolazy -r ts-node/register --inspect=127.0.0.1:9228 ./src/spankchain/main.ts chainsaw" "node --nolazy -r ts-node/register --inspect ./src/spankchain/main.ts"
else
    node --nolazy -r ts-node/register ./src/spankchain/main.ts "${@}"
fi
