#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

if [[ "$#" -ne 2 ]]; then
    echo "USAGE: $0 BOOTY ADDRESS"
    echo "Sends BOOTY to ADDRESS."
    exit 1
fi

AMOUNT="$(awk "BEGIN { print $1 * 1e18 }")"
ADDRESS="$2"

echo "Sending $AMOUNT BEI to $ADDRESS..."

(
    echo "(await HumanStandardToken.at('0xd01c08c7180eae392265d8c7df311cf5a93f1b73')).transfer('$ADDRESS', '$AMOUNT')"
    # Note: this needs to be Large Enough that truffle console can start and
    # the transaction can be sent, otherwise truffle terminates before the
    # transaction is sent (ex, waiting for the result of eth_gasPrice).
    sleep 20

) | ./truffle console
echo "" # return console to nice state