#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

if [[ "$#" -lt 1 ]]; then
    echo "USAGE: $0 PSQL_ARG [PSQL_ARG ...]"
    echo "Where PSQL_ARGs are arguments to be passed to 'psql'"
    exit 1
fi

make
for f in build/*.sql; do
    echo
    echo "Loading '$f'..."
    psql -v ON_ERROR_STOP=1 "${@}" < "$f"
    echo 'Done!'
done
