#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

DB="sc-hub-sql-tests"
dropdb --if-exists "$DB" || true
createdb "$DB"

cd ../../
DATABASE_URL="postgres:///$DB" yarn migrate
cd -

outf="/tmp/sc-hub-sql-tests-output"
for f in tests/*.sql; do
    echo
    echo
    echo
    echo "Running: $f"
    psql -a "$DB" < "$f" > "$outf" 2>&1
    diff -u "$f.expected" "$outf" || {
        echo
        echo "hint: run:"
        echo "  cp $outf \"$PWD/$f.expected\""
        exit 1
    }
    echo "Okay!"
done
