/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
import { TransactionObject, BlockType } from "web3/eth/types";
import { Callback, EventLog } from "web3/types";
import { EventEmitter } from "events";
import { Provider } from "web3/providers";

export class ECTools {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  _address: string;
  options: contractOptions;
  methods: {
    recoverSigner(
      _hashedMsg: string | number[],
      _sig: string
    ): TransactionObject<string>;

    isSignedBy(
      _hashedMsg: string | number[],
      _sig: string,
      _addr: string
    ): TransactionObject<boolean>;

    hexstrToBytes(_hexstr: string): TransactionObject<(string)[]>;

    parseInt16Char(_char: string): TransactionObject<string>;

    uintToBytes32(_uint: number | string): TransactionObject<(string)[]>;

    toEthereumSignedMessage(_msg: string): TransactionObject<string>;

    uintToString(_uint: number | string): TransactionObject<string>;

    substring(
      _str: string,
      _startIndex: number | string,
      _endIndex: number | string
    ): TransactionObject<string>;
  };
  deploy(options: {
    data: string;
    arguments: any[];
  }): TransactionObject<Contract>;
  events: {
    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: string[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: string[];
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>;
  setProvider(provider: Provider): void;
}
