CREATE or replace VIEW cm_channel_updates AS
  SELECT cu.id,
         cu.channel_id,
         cu.created_on,
         cu.reason,
         cu.args,
         cu.originator,
         cu."user",
         cu.invalid,
         cu.hub_signed_on,
         cu.user_signed_on,
         cu.recipient,
         cu.balance_wei_hub,
         cu.balance_wei_user,
         cu.balance_token_hub,
         cu.balance_token_user,
         cu.pending_deposit_wei_hub,
         cu.pending_deposit_wei_user,
         cu.pending_deposit_token_hub,
         cu.pending_deposit_token_user,
         cu.pending_withdrawal_wei_hub,
         cu.pending_withdrawal_wei_user,
         cu.pending_withdrawal_token_hub,
         cu.pending_withdrawal_token_user,
         cu.tx_count_global,
         cu.tx_count_chain,
         cu.thread_root,
         cu.thread_count,
         cu.timeout,
         cu.sig_hub,
         cu.sig_user,
         cu.chainsaw_event_id,
         cu.chainsaw_resolution_event_id,
         cu.onchain_tx_logical_id,
         c.contract
  FROM (_cm_channel_updates cu
    JOIN cm_channels c ON ((c.id = cu.channel_id)));


