#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

if [ ! -e ~/.parity/data ]; then
    echo "Error: run './parity-reset' first"
    exit 1
fi

echo -e '\n' > ~/.parity/empty-password

~/.parity/bin/parity --config dev --base-path=~/.parity/data --unlock 0x00a329c0648769a73afac7f9381e08fb43dbea72 --password ~/.parity/empty-password --jsonrpc-cors=all --jsonrpc-hosts=all --jsonrpc-port 12123
